var getCalendario = function(fechaInicio, dias, fechaFin){
	fechaInicio.datepicker({
		closeText : jQuery.i18n.prop('calendario.cerrar'),
		prevText : jQuery.i18n.prop('calendario.ant'),
		nextText : jQuery.i18n.prop('calendario.sig'),
		currentText : jQuery.i18n.prop('calendario.hoy'),
		dateFormat : 'dd/mm/yy',
		minDate : 0,
		maxDate: dias,
		monthNames : [ jQuery.i18n.prop('calendario.enero'),
				jQuery.i18n.prop('calendario.febrero'),
				jQuery.i18n.prop('calendario.marzo'),
				jQuery.i18n.prop('calendario.abril'),
				jQuery.i18n.prop('calendario.mayo'),
				jQuery.i18n.prop('calendario.junio'),
				jQuery.i18n.prop('calendario.julio'),
				jQuery.i18n.prop('calendario.agosto'),
				jQuery.i18n.prop('calendario.septiembre'),
				jQuery.i18n.prop('calendario.octubre'),
				jQuery.i18n.prop('calendario.noviembre'),
				jQuery.i18n.prop('calendario.diciembre') ],
		monthNamesShort : [ jQuery.i18n.prop('calendario.ene'),
				jQuery.i18n.prop('calendario.feb'),
				jQuery.i18n.prop('calendario.mar'),
				jQuery.i18n.prop('calendario.abr'),
				jQuery.i18n.prop('calendario.may'),
				jQuery.i18n.prop('calendario.jun'),
				jQuery.i18n.prop('calendario.jul'),
				jQuery.i18n.prop('calendario.ago'),
				jQuery.i18n.prop('calendario.sep'),
				jQuery.i18n.prop('calendario.oct'),
				jQuery.i18n.prop('calendario.nov'),
				jQuery.i18n.prop('calendario.dic') ],
		dayNamesMin : [ jQuery.i18n.prop('calendario.do'),
				jQuery.i18n.prop('calendario.lu'),
				jQuery.i18n.prop('calendario.ma'),
				jQuery.i18n.prop('calendario.mi'),
				jQuery.i18n.prop('calendario.ju'),
				jQuery.i18n.prop('calendario.vi'),
				jQuery.i18n.prop('calendario.sa') ],
		dayNames : [ jQuery.i18n.prop('calendario.domingo'),
				jQuery.i18n.prop('calendario.lunes'),
				jQuery.i18n.prop('calendario.martes'),
				jQuery.i18n.prop('calendario.miercoles'),
				jQuery.i18n.prop('calendario.jueves'),
				jQuery.i18n.prop('calendario.viernes'),
				jQuery.i18n.prop('calendario.sabado') ],
		dayNamesShort : [ jQuery.i18n.prop('calendario.dom'),
				jQuery.i18n.prop('calendario.lun'),
				jQuery.i18n.prop('calendario.mar'),
				jQuery.i18n.prop('calendario.mie'),
				jQuery.i18n.prop('calendario.jue'),
				jQuery.i18n.prop('calendario.vie'),
				jQuery.i18n.prop('calendario.sab') ],
		firstDay : 1,
		isRTL : false,
		showMonthAfterYear : false,
		yearSuffix : '',
		onSelect : function() {
			if (undefined!==fechaFin){
				fechaFin.datepicker('setDate', $(this).datepicker('getDate'));
				fechaFin.datepicker('option', 'minDate', $(this).datepicker('getDate'));
			}
		}
	});
	
};